[package]
name = "limited-queue"
version = "0.1.4"
edition = "2021"
authors = ["Tzu-Ching Yang"]
description = "a limited queue that overrides the oldest data if trying to push a data when the queue is full."
license = "MIT"

[dependencies]

[dev-dependencies]
rand = "0.8.5"
